version: '3.8'

services:
  ums-frontend:
    build:
      context: .
      args:
        - PUBLISH_DIR=${PUBLISH_DIR:-dist}
    container_name: ums-frontend
    ports:
      - '4003:4003'
    restart: always
