export const menuConfig: Menu.MenuItem[] = [
  {
    label: 'Core Administrative Services',
    slug: 'core-administrative-services',
    category: 'Administrative',
    icon: 'school',
    colorScheme: 'red',
    description: 'Dashboard • Courses • Progress • Finance • Profile',

    children: [
      {
        label: 'User Management',
        slug: 'user-managemnt',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'blue',
        children: [],
      },
      {
        label: 'Location Management',
        slug: 'location',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/home/sub-menu/location',
        icon: 'edit_location',
        colorScheme: 'blue',
        children: [
          {
            label: 'State',
            description: 'Manage states and union territories',
            path: '/master/location/states',
            icon: 'globe',
            colorScheme: 'blue',
          },
          {
            label: 'Division',
            description: 'Manage divisions',
            path: '/master/location/divisions',
            icon: 'folder',
            colorScheme: 'blue',
          },
          {
            label: 'District',
            description: 'Manage districts',
            path: '/master/location/districts',
            icon: 'map',
            colorScheme: 'blue',
          },
          {
            label: 'Tehsil',
            description: 'Manage tehsils',
            path: '/master/location/tehsils',
            icon: 'location_city',
            colorScheme: 'blue',
          },
          {
            label: 'Block',
            description: 'Manage blocks',
            path: '/master/location/blocks',
            icon: 'grid_view',
            colorScheme: 'blue',
          },
        ],
      },
      {
        label: 'Subject Management',
        slug: 'subject',
        description: 'Manage subject , categories, and more.',
        path: '/home/sub-menu/subject',
        icon: 'menu_book',
        colorScheme: 'purple',
        children: [
          {
            label: 'Mode Of Education',
            description: 'Manage Mode of Education',
            path: '/master/subject/programme-mode-of-education',
            icon: 'apartment',
            colorScheme: 'purple',
          },
          {
            label: 'Subject Category',
            description: 'Manage Subject Category',
            path: '/master/subject/subject-category',
            icon: 'apartment',
            colorScheme: 'purple',
          },
          {
            label: 'Subject ',
            description: 'Manage Subject',
            path: '/master/subject/subjects',
            icon: 'apartment',
            colorScheme: 'purple',
          },
          {
            label: 'Programme Specialization Structure',
            description: 'Programme Specialization Structure',
            path: '/master/subject/programme-specialization-structure',
            icon: 'apartment',
            colorScheme: 'purple',
          },
        ],
      },

      {
        label: 'Faculty Admin',
        slug: 'faculty-management',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/faculty-management',
        icon: 'apartment',
        colorScheme: 'green',
        children: [
          {
            label: 'Office Type',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/master/faculty-management/office-type',
            icon: 'apartment',
            colorScheme: 'green',
          },
          {
            label: 'Department',
            description: 'Manage departments',
            path: '/master/faculty-management/department',
            icon: 'domain',
            colorScheme: 'green',
          },
          {
            label: 'Designation',
            description: 'Manage designations',
            path: '/master/faculty-management/designation',
            icon: 'badge',
            colorScheme: 'green',
          },
          {
            label: 'Faculty',
            description: 'Manage faculties',
            path: '/master/faculty-management/faculty',
            icon: 'groups',
            colorScheme: 'green',
          },
        ],
      },
      {
        label: 'Human Resource',
        slug: 'hr',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/hr',
        icon: 'apartment',
        colorScheme: 'red',
        children: [
          {
            label: 'Caste',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/master/hr/caste',
            icon: 'apartment',
            colorScheme: 'red',
          },
          {
            label: 'Post',
            description: 'Manage posts and positions',
            path: '/master/hr/post',
            icon: 'work',
            colorScheme: 'red',
          },
          {
            label: 'Religion',
            description: 'Manage religions',
            path: '/master/hr/religion',
            icon: 'domain',
            colorScheme: 'red',
          },
          {
            label: 'Qualification',
            description: 'Manage qualifications',
            path: '/master/hr/qualification',
            icon: 'badge',
            colorScheme: 'red',
          },
          {
            label: 'Class',
            description: 'Manage classes',
            path: '/master/hr/class',
            icon: 'class',
            colorScheme: 'red',
          },
          {
            label: 'Section',
            description: 'Manage sections',
            path: '/master/hr/section',
            icon: 'segment',
            colorScheme: 'red',
          },
          {
            label: 'Designation Type',
            description: 'Manage designation types',
            path: '/master/hr/designation-type',
            icon: 'category',
            colorScheme: 'red',
          },
          {
            label: 'Designation',
            description: 'Manage designations',
            path: '/master/hr/designation',
            icon: 'badge',
            colorScheme: 'red',
          },
        ],
      },
      {
        label: 'College',
        slug: 'college',
        description: 'Manage college types and Categorys.',
        path: '/home/sub-menu/college',
        icon: 'school',
        colorScheme: 'indigo',
        children: [
          {
            label: 'College Type',
            description: 'Manage college types',
            path: '/master/college/college-type',
            icon: 'school',
            colorScheme: 'indigo',
          },
          {
            label: 'Category',
            description: 'Manage college categories',
            path: '/master/college/college-category',
            icon: 'school',
            colorScheme: 'red',
          },
        ],
      },
      {
        label: 'Other Masters',
        slug: 'other',
        description: 'Manage masters.',
        path: '/home/sub-menu/other',
        icon: 'school',
        colorScheme: 'indigo',
        children: [
          {
            label: 'Degree Level',
            description: 'Manage degree levels',
            path: '/master/other/degree-level',
            icon: 'school',
            colorScheme: 'indigo',
          },
          {
            label: 'Academic Year',
            description: 'Manage academic year records and session details',
            path: '/master/other/academic-year',
            icon: 'school',
            colorScheme: 'indigo',
          },
          {
            label: 'Programme',
            description: 'Manage programmes',
            path: '/master/other/programme',
            icon: 'school',
            colorScheme: 'indigo',
          },
          {
            label: 'Specialisation',
            description: 'Manage specialisations',
            path: '/master/other/specialisation',
            icon: 'school',
            colorScheme: 'indigo',
          },
          {
            label: 'Nationality',
            description: 'Manage nationalities',
            path: '/master/other/nationality',
            icon: 'school',
            colorScheme: 'indigo',
          },
        ],
      },
      {
        label: 'Grant',
        slug: 'grant',
        description: 'Manage grant types and categories.',
        path: '/home/sub-menu/grant',
        icon: 'workspace_premium',
        colorScheme: 'purple',
        children: [
          {
            label: 'Grant Type',
            description: 'Manage grant types',
            path: '/master/grant/grant-type',
            icon: 'workspace_premium',
            colorScheme: 'purple',
          },
          {
            label: 'Grant Category',
            description: 'Manage grant categories',
            path: '/master/grant/grant-category',
            icon: 'category',
            colorScheme: 'purple',
          },
          {
            label: 'Eligibility Application Process',
            description: 'Manage eligibility criteria and application process',
            path: '/master/grant/eligibility-application-process',
            icon: 'assignment_turned_in',
            colorScheme: 'purple',
          },
        ],
      },
      {
        label: 'Scheme',
        slug: 'scheme',
        description: 'Manage scheme types and categories.',
        path: '/home/sub-menu/scheme',
        icon: 'assignment',
        colorScheme: 'teal',
        children: [
          {
            label: 'Scheme Type',
            description: 'Manage scheme types',
            path: '/master/scheme/scheme-type',
            icon: 'assignment',
            colorScheme: 'teal',
          },
          {
            label: 'Scheme Category',
            description: 'Manage scheme categories',
            path: '/master/scheme/scheme-category',
            icon: 'category',
            colorScheme: 'teal',
          },
          {
            label: 'Schemes',
            description: 'Manage schemes',
            path: '/master/scheme/schemes',
            icon: 'assignment',
            colorScheme: 'teal',
          },
        ],
      },
    ],
  },
  {
    label: 'Employee\nServices',
    slug: 'employee-services',
    category: 'Employee',
    icon: 'groups',
    colorScheme: 'red',
    description: 'Classes • Grades • Advising • Resources',
    children: [
      {
        label: 'Employee Management System',
        slug: 'employee-management-system',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/home/sub-menu/employee-management-system',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [
          {
            label: 'Settings',
            slug: 'settings',
            description:
              'Manage employee management system settings and masters.',
            path: '/home/sub-menu/settings',
            icon: 'settings',
            colorScheme: 'red',
            children: [
              {
                label: 'Nature of Employment',
                slug: 'nature-of-employment',
                description: 'Manage nature of employment master data.',
                path: '/master/employee/settings/nature-of-employment',
                icon: 'work',
                colorScheme: 'red',
                children: [],
              },
              {
                label: 'Document Option',
                slug: 'document-option',
                description: 'Manage document option master data.',
                path: '/master/employee/settings/document-option',
                icon: 'description',
                colorScheme: 'red',
                children: [],
              },
              {
                label: 'Action Options',
                slug: 'action-options',
                description: 'Manage action options master data.',
                path: '/master/employee/settings/action-option',
                icon: 'settings_accessibility',
                colorScheme: 'red',
                children: [],
              },
              {
                label: 'Subject Specialization',
                slug: 'subject-specialization',
                description: 'Manage subject specialization master data.',
                path: '/master/employee/settings/subject-specialization',
                icon: 'menu_book',
                colorScheme: 'red',
                children: [],
              },
              {
                label: 'Travel Purpose',
                slug: 'travel-purpose',
                description: 'Manage travel purpose master data.',
                path: '/master/employee/settings/travel-purpose',
                icon: 'travel_explore',
                colorScheme: 'red',
                children: [],
              },
            ],
          },
        ],
      },
      {
        label: 'Career Advancement',
        slug: 'career-advancement',
        description: 'Manage career advancement sessions and assessments.',
        path: '/home/sub-menu/career-advancement',
        icon: 'trending_up',
        colorScheme: 'orange',
        children: [
          {
            label: 'APAR — All Applications',
            slug: 'apar-application',
            description: 'Initiate and manage APAR for all employees',
            path: '/career-advancement/apar-application/all',
            icon: 'assignment',
            colorScheme: 'orange',
          },
          {
            label: 'Sessions Management',
            slug: 'sessions-management',
            description:
              'Manage assessment sessions for career advancement programs.',
            path: '/career-advancement/sessions-management',
            icon: 'event',
            colorScheme: 'orange',
          },
          {
            label: 'Employee Self Assessment',
            slug: 'employee-self-assessment',
            description:
              'APAR Employee Self Assessment and performance reviews.',
            path: '/career-advancement/employee-self-assessment',
            icon: 'assignment',
            colorScheme: 'red',
          },
          {
            label: 'Performance Appraisal System',
            slug: 'performance-appraisal-system',
            description:
              'APAR Employee Self Assessment and performance reviews.',
            path: '/career-advancement/performance-appraisal-system',
            icon: 'assignment',
            colorScheme: 'red',
          },
        ],
      },
    ],
  },
  {
    label: 'Academics',
    slug: 'academics',
    category: 'Academics',
    icon: 'grid_view',
    colorScheme: 'red',
    description: 'Manage registrar and admin functions',
    navigationStyle: 'sidebar',
    children: [
      {
        label: 'Programme Management',
        slug: 'programme-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Admission Admin Guide',
        slug: 'admission-admin-guide',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Academics',
        slug: 'academics',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Evaluation & Grading',
        slug: 'evaluation-&-grading',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Exam Management',
        slug: 'examination-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Certificate Management',
        slug: 'certificate-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Feedback Management',
        slug: 'student-feedback-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Student Additional Information',
        slug: 'student-additional-information',
        description: 'Manage student additional details.',
        path: '/sis/student-additional-information',
        icon: 'person_add',
        colorScheme: 'red',
      },
      {
        label: 'Student Application Form',
        slug: 'student-application-form',
        description: 'Create and submit student applications.',
        path: '/sis/student-application-form',
        icon: 'assignment',
        colorScheme: 'red',
      },
      {
        label: 'Fee Payment Approval (Temp)',
        slug: 'student-fee-approval',
        description: 'Approve student application fee payments.',
        path: '/sis/student-fee-approval',
        icon: 'check_circle',
        colorScheme: 'red',
      },
    ],
  },
  {
    label: 'Accounts And Finance',
    slug: 'accounts-and-finance',
    category: 'Finance',
    icon: 'menu_book',
    colorScheme: 'red',
    description: 'Streamline curriculum management and approvals',
    children: [
      {
        label: 'Financial Supply Chain Management',
        slug: 'financial-supply-chain-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
    ],
  },
  {
    label: 'Governance',
    slug: 'governance',
    category: 'Governance',
    icon: 'bolt',
    colorScheme: 'red',
    description: 'Track student competencies and skill development',
    children: [
      {
        label: 'Affiliation Management',
        slug: 'affiliation-Management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Communication System',
        slug: 'core-communication-system',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Grievance Management',
        slug: 'grievance-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Residential Allocation',
        slug: 'residential-allocation-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
      {
        label: 'Hostel Managemnet',
        slug: 'hostel-management',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        icon: 'edit_location',
        colorScheme: 'red',
        children: [],
      },
    ],
  },
  // {
  //   label: 'Career\nGateway',
  //   slug: 'career-gateway',
  //   category: 'HR',
  //   icon: 'work',
  //   colorScheme: 'red',
  //   description: 'Career services and job placement resources',
  // },
  // {
  //   label: 'ICON – Research Compliance',
  //   slug: 'icon-research-compliance',
  //   category: 'Academics',
  //   icon: 'science',
  //   colorScheme: 'orange',
  //   description: 'Manage research compliance and ethics approvals',
  // },
  // {
  //   label: 'Disability\nCenter',
  //   slug: 'disability-center',
  //   category: 'HR',
  //   icon: 'accessible',
  //   colorScheme: 'pink',
  //   description: 'Support services for students with disabilities',
  // },
  // {
  //   label: 'Student ID & Campus Allowance',
  //   slug: 'student-id-campus-allowance',
  //   category: 'Finance',
  //   icon: 'credit_card',
  //   colorScheme: 'blue',
  //   description: 'Manage student IDs and campus financial allowances',
  // },
  // {
  //   label: 'University Queue – Virtual Queuing',
  //   slug: 'university-queue-virtual-queuing',
  //   category: 'Operation',
  //   icon: 'desktop_windows',
  //   colorScheme: 'purple',
  //   description: 'Virtual queuing system for campus services',
  // },
  // {
  //   label: 'FIXIT — Facility Management',
  //   slug: 'fixit-facility-management',
  //   category: 'Operation',
  //   icon: 'build',
  //   colorScheme: 'teal',
  //   description: 'Report and manage facility maintenance issues',
  // },
  // {
  //   label: 'Scholarship&\nGrants',
  //   slug: 'scholarship-grants',
  //   category: 'Finance',
  //   icon: 'workspace_premium',
  //   colorScheme: 'indigo',
  //   description: 'Manage scholarship and grant applications',
  // },
];
