export const menuConfig: Menu.MenuItem[] = [
  {
    label: 'Student Information System',
    slug: 'student-information-system',
    category: 'Academics',
    icon: 'school',
    colorScheme: 'blue',
  },
  {
    label: 'Faculty Portal',
    slug: 'faculty-portal',
    category: 'HR',
    icon: 'groups',
    colorScheme: 'purple',
  },
  {
    label: 'Registrar / Admin Dashboard',
    slug: 'registrar-admin-dashboard',
    category: 'Academics',
    icon: 'grid_view',
    colorScheme: 'gray',
  },
  {
    label: 'Curriculog — Curriculum Governance',
    slug: 'curriculog-curriculum-governance',
    category: 'Academics',
    icon: 'menu_book',
    colorScheme: 'green',
  },
  {
    label: 'Competency Tracking',
    slug: 'competency-tracking',
    category: 'Academics',
    icon: 'bolt',
    colorScheme: 'orange',
  },
  {
    label: 'Career Gateway',
    slug: 'career-gateway',
    category: 'HR',
    icon: 'work',
    colorScheme: 'red',
  },
  {
    label: 'ICON – Research Compliance',
    slug: 'icon-research-compliance',
    category: 'Academics',
    icon: 'science',
    colorScheme: 'orange',
  },
  {
    label: 'Disability Center',
    slug: 'disability-center',
    category: 'HR',
    icon: 'accessible',
    colorScheme: 'pink',
  },
  {
    label: 'Student ID & Campus Allowance',
    slug: 'student-id-campus-allowance',
    category: 'Finance',
    icon: 'credit_card',
    colorScheme: 'blue',
  },
  {
    label: 'University Queue – Virtual Queuing',
    slug: 'university-queue-virtual-queuing',
    category: 'Operation',
    icon: 'desktop_windows',
    colorScheme: 'purple',
  },
  {
    label: 'FIXIT — Facility Management',
    slug: 'fixit-facility-management',
    category: 'Operation',
    icon: 'build',
    colorScheme: 'teal',
  },
  {
    label: 'Scholarship & Grants',
    slug: 'scholarship-grants',
    category: 'Finance',
    icon: 'workspace_premium',
    colorScheme: 'indigo',
  },
  {
    label: 'Master Data Management',
    slug: 'master-data',
    category: 'Admin',
    icon: 'settings',
    colorScheme: 'amber',
    children: [
      {
        label: 'Location',
        description: 'Manage countries, states, cities, and campus locations.',
        path: '/master/location',
        icon: 'location_on',
        colorScheme: 'blue',
      },
      {
        label: 'Subject Category',
        description:
          'Manage categories and classifications for academic subjects.',
        path: '/master/subject-category',
        icon: 'category',
        colorScheme: 'purple',
      },
      {
        label: 'Office Type',
        description:
          'Manage different types of faculty and administrative offices.',
        path: '/master/office-type',
        icon: 'apartment',
        colorScheme: 'green',
      },
    ],
  },
];
