export const menuConfig: Menu.MenuItem[] = [
  {
    label: 'Student Information System',
    slug: 'student-information-system',
    category: 'Academics',
    icon: 'school',
    colorScheme: 'blue',
  },
  {
    label: 'Faculty Portal',
    slug: 'faculty-portal',
    category: 'HR',
    icon: 'groups',
    colorScheme: 'purple',
  },
  {
    label: 'Registrar / Admin Dashboard',
    slug: 'registrar-admin-dashboard',
    category: 'Academics',
    icon: 'grid_view',
    colorScheme: 'gray',
  },
  {
    label: 'Curriculog — Curriculum Governance',
    slug: 'curriculog-curriculum-governance',
    category: 'Academics',
    icon: 'menu_book',
    colorScheme: 'green',
  },
  {
    label: 'Competency Tracking',
    slug: 'competency-tracking',
    category: 'Academics',
    icon: 'bolt',
    colorScheme: 'orange',
  },
  {
    label: 'Career Gateway',
    slug: 'career-gateway',
    category: 'HR',
    icon: 'work',
    colorScheme: 'red',
  },
  {
    label: 'ICON – Research Compliance',
    slug: 'icon-research-compliance',
    category: 'Academics',
    icon: 'science',
    colorScheme: 'orange',
  },
  {
    label: 'Disability Center',
    slug: 'disability-center',
    category: 'HR',
    icon: 'accessible',
    colorScheme: 'pink',
  },
  {
    label: 'Student ID & Campus Allowance',
    slug: 'student-id-campus-allowance',
    category: 'Finance',
    icon: 'credit_card',
    colorScheme: 'blue',
  },
  {
    label: 'University Queue – Virtual Queuing',
    slug: 'university-queue-virtual-queuing',
    category: 'Operation',
    icon: 'desktop_windows',
    colorScheme: 'purple',
  },
  {
    label: 'FIXIT — Facility Management',
    slug: 'fixit-facility-management',
    category: 'Operation',
    icon: 'build',
    colorScheme: 'teal',
  },
  {
    label: 'Scholarship & Grants',
    slug: 'scholarship-grants',
    category: 'Finance',
    icon: 'workspace_premium',
    colorScheme: 'indigo',
  },
  {
    label: 'Master Data Management',
    slug: 'master-data',
    category: 'Admin',
    icon: 'settings',
    colorScheme: 'amber',
    children: [
      {
        label: 'Location Management',
        slug: 'location',
        description:
          'Manage countries, states, divisions, districts, tehsils, and blocks.',
        path: '/home/sub-menu/location',
        icon: 'edit_location',
        colorScheme: 'blue',
        children: [
          {
            label: 'State',
            description: 'Manage states and union territories',
            path: '/master/location/states',
            icon: 'globe',
            colorScheme: 'blue',
          },
          {
            label: 'Division',
            description: 'Manage divisions',
            path: '/master/location/divisions',
            icon: 'folder',
            colorScheme: 'blue',
          },
          {
            label: 'District',
            description: 'Manage districts',
            path: '/master/location/districts',
            icon: 'map',
            colorScheme: 'blue',
          },
          {
            label: 'Tehsil',
            description: 'Manage tehsils',
            path: '/master/location/tehsils',
            icon: 'location_city',
            colorScheme: 'blue',
          },
          {
            label: 'Block',
            description: 'Manage blocks',
            path: '/master/location/blocks',
            icon: 'grid_view',
            colorScheme: 'blue',
          },
        ],
      },
      {
        label: 'Course Management',
        slug: 'course',
        description: 'Manage course departments, subject categories, and more.',
        path: '/home/sub-menu/course',
        icon: 'menu_book',
        colorScheme: 'purple',
        children: [
          {
            label: 'Course Department',
            description: 'Manage course departments',
            path: '/master/course/course-department',
            icon: 'apartment',
            colorScheme: 'purple',
          },
          {
            label: 'Course Level',
            description: 'Manage Course Level',
            path: '/master/course/course-level',
            icon: 'apartment',
            colorScheme: 'purple',
          },
          {
            label: 'Course Exam Type',
            description: 'Manage Course Exam Type',
            path: '/master/course/course-exam-type',
            icon: 'apartment',
            colorScheme: 'purple',
          },
        ],
      },
      {
        label: 'Faculty & Org Management',
        slug: 'faculty-management',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/faculty-management',
        icon: 'apartment',
        colorScheme: 'green',
        children: [
          {
            label: 'Office Type',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/master/faculty-management/office-type',
            icon: 'apartment',
            colorScheme: 'green',
          },
          {
            label: 'Department',
            description: 'Manage departments',
            path: '/master/faculty-management/department',
            icon: 'domain',
            colorScheme: 'green',
          },
          {
            label: 'Designation',
            description: 'Manage designations',
            path: '/master/faculty-management/designation',
            icon: 'badge',
            colorScheme: 'green',
          },
        ],
      },
      {
        label: 'Human Resource',
        slug: 'hr',
        description: 'Manage office types, departments, and designations.',
        path: '/home/sub-menu/hr',
        icon: 'apartment',
        colorScheme: 'red',
        children: [
          {
            label: 'Caste',
            description:
              'Manage different types of faculty and administrative offices.',
            path: '/master/hr/caste',
            icon: 'apartment',
            colorScheme: 'red',
          },
          {
            label: 'Religion',
            description: 'Manage religions',
            path: '/master/hr/religion',
            icon: 'domain',
            colorScheme: 'red',
          },
          {
            label: 'Qualification',
            description: 'Manage qualifications',
            path: '/master/hr/qualification',
            icon: 'badge',
            colorScheme: 'red',
          },
        ],
      },
    ],
  },
];
